services:
  php-fpm:
    image: php:8.1.30-fpm-alpine
    container_name: singles-conscientes
    working_dir: /var/www/html/sc
    command: 'php -S 0.0.0.0:8000'
    ports:
      - '80:8000'
    volumes:
      - './src:/var/www/html/sc'